### PR TITLE
Move bin/bench_crawl and bin/bench_upload to the benchbox branch

### PR DESCRIPTION
**Pull request by xeno-by**
In our experience with maintaining the Rsc benchmark infrastructure, we observed several situations when supporting scripts (`bin/bench_crawl` and `bin/bench_upload`) broke because of changes in the benchbox environment, invalidating code that's been committed into master.

This suggests that these scripts don't belong in master. Much like performance data that lives in the `performance` branch, supporting scripts must have the flexibility to evolve separately in order to avoid the breakages described above.

As a result, this pull request moves the scripts into the newly created `benchbox` branch. In that branch, we'll be able to work on our benchmark infrastructure without breaking existing code.

### CODE REVIEW

**Comment by rscbenchbox** [comment]
Accepted benchmarking [5c33425](https://github.com/xeno-by/reasonable-scala/commit/5c33425cf41d16e5337171c90fae13bbbca6fdd8). This may take a while.

**Comment by rscbenchbox** [comment]
Accepted benchmarking [f4eb700](https://github.com/xeno-by/reasonable-scala/commit/f4eb700098fa2c1923771efbc5c13b96f199471f). This may take a while.

**Comment by rscbenchbox** [comment]
Finished benchmarking [f4eb700](https://github.com/xeno-by/reasonable-scala/commit/f4eb700098fa2c1923771efbc5c13b96f199471f).

| Benchmark          | Before | After |
|--------------------|--------|-------|
| RscNativeTypecheck | 63.438 ms     | 63.727 ms    |
| RscTypecheck       | 24.922 ms     | 25.160 ms    |

Full results are available at https://github.com/twitter/reasonable-scala/commit/b46239bbe6adb71a6a2b7c0254cf81dbcc171c40.

**Comment by xeno-by** [comment]
@rscbenchbox Thank you!

**Pull request merged**
